config/routes.rb
Rails.application.routes.draw do

  resources :moves
  resources :games
  resources :players
  get  'play' => "home#play"
  get '/games/start/:id', to: 'games#start', as: 'start_game'
  get '/home/play/:move', to: 'home#play', as: 'playnewgame'
  post '/games/next_move/:move/:current_player', to: 'games#next_move', as: 'nextmovegame'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
require 'connectfourgame'

class Game < ApplicationRecord

    attr_accessor :move, :board, :engine, :ai

    has_many :moves
	has_many :players, through: :moves

	def start	 
	  sgame = ConnectFour.new	
      @move = Move.new     
	  @engine = sgame.engine 
	  @board = sgame.board 
	  @ai = sgame.ai
	  nmove = @ai.next_move @board
    end   		 
	     	

    def save_move(mv,player,sign)
        @move.player_id = player
        @move.game_id = self.id
        @board.drop_coin(mv,sign)
        @move.boardmatrix = @board.simple_render
        @move.save
    end

    def ai
    	@ai
    end

    def board
    	@board
    end
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/models/player.rb
class Player < ApplicationRecord
	validates :user_name, presence: true
	has_many :moves
	has_many :games, through: :moves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :start, :next_move]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  def start
      sign="0"
      @move = @game.start
      @game.save_move(@move,@game.second_player,sign)
      redirect_to playnewgame_url(@move)
      #render :template => "home/play"s
  end

  def next_move
    player =  params[:current_player]
    move =  params[:move]
    if( player == 2) then #bot
      sign="0"
    else
      sign="X"
    end
    @game.save_move(move,player,sign)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:first_player, :second_player, :created, :game_status, :game_type, :first_player_piece_code,:current_player, :move)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

  end

  def play
  	@move=params[:move].to_i+1 #AI algorythm is generating movements from 0-6 so we add 1 more
  	gon.move = @move
  end


end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:user_name, :password_hash, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_player, class: 'form-control-label' %>
    <%= form.number_field :first_player, id: :game_first_player, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :second_player, class: 'form-control-label' %>
    <%= form.number_field :second_player, id: :game_second_player, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :created, class: 'form-control-label' %>
    <%= form.datetime_select :created, id: :game_created, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :game_status, class: 'form-control-label' %>
    <%= form.text_field :game_status, id: :game_game_status, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :game_type, class: 'form-control-label' %>
    <%= form.text_field :game_type, id: :game_game_type, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :first_player_piece_code, class: 'form-control-label' %>
    <%= form.text_field :first_player_piece_code, id: :game_first_player_piece_code, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table class="table table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>First player</th>
      <th>Second player</th>
      <th>Created</th>
      <th>Game status</th>
      <th>Game type</th>
      <th>First player piece code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.first_player %></td>
        <td><%= game.second_player %></td>
        <td><%= game.created %></td>
        <td><%= game.game_status %></td>
        <td><%= game.game_type %></td>
        <td><%= game.first_player_piece_code %></td>
        <td><%= link_to 'Play', start_game_url(game)%></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td> 
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class: 'btn btn-secondary' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First player:</strong>
  <%= @game.first_player %>
</p>

<p>
  <strong>Second player:</strong>
  <%= @game.second_player %>
</p>

<p>
  <strong>Created:</strong>
  <%= @game.created %>
</p>

<p>
  <strong>Game status:</strong>
  <%= @game.game_status %>
</p>

<p>
  <strong>Game type:</strong>
  <%= @game.game_type %>
</p>

<p>
  <strong>First player piece code:</strong>
  <%= @game.first_player_piece_code %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
<h1></h1>
<p>Code Challenge</p>
<div class="jumbotron">
  <h1 class="display-3">ConnectFour</h1>
  <p class="lead">Code Challenge</p>
  <hr class="my-4">
  <p class="lead">
 		<%= link_to "Game Setup", games_path ,class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/home/play.html.erb
<h1>ConnectFour <%=@move %></h1>


<h3>Computer last move : <%=@move %> </h3>
<script type="text/javascript">
	//alert(gon.move)
	//function changeImage(gon.move) {
		myimg="img"+gon.move;
        document.getElementById(myimg).src="/assets/letter-x.jpg";
        document.getElementById(myimg).class="imagebox";
        document.getElementById(myimg).id=myimg;
        //document.getElementById(myimg).src.disabled = true;
    //}

</script>
<div class="row">
	  <div class="card-deck">
	  <img class="cells"  src="/assets/cells.jpg">
	  </div>
</div>

<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img50" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img50",49);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img51" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img51",49);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img52" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img52",49);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img53" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img53",49);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img54" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img54",49);';'>
	  </div>
	  <div class="card">
	      <img class="imageboxempty" id="img55" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img55",49);';'>
	  </div>
	  <div class="card">
	      <img class="imageboxempty" id="img56" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img56",49);';'>
	  </div>
	</div>
</div>

<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img43" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img43",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img44" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img44",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img45" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img45",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img46" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img46",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img47" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img47",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img48" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img48",42);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img49" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img49",42);';'>
	  </div>
	</div>
</div>


<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img36" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img36",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img37" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img37",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img38" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img38",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img39" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img39",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img40" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img40",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img41" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img41",35);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img42" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img42",35);';'>
	  </div>
	</div>
</div>

<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img29" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img29",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img30" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img30",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img31" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img31",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img32" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img32",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img33" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img33",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img34" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img34",28);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img35" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img35",28);';'>
	  </div>
	</div>
</div>

<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img22" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img22",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img23" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img23",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img24" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img24",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img25" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img25",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img26" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img26",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img27" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img27",21);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img28" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img28",21);';'>
	  </div>
	</div>
</div>



<div class="row">
	  <div class="card-deck">
	  <div class="card">
	     <img class="imageboxempty" id="img15" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img15",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img16" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img16",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img17" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img17",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img18" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img18",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img19" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img19",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img20" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img20",14);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img21" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img21",14);';'>
	  </div>
	</div>
</div>
<div class="row">
	  <div class="card-deck">
	  <div class="card">
         <img class="imageboxempty" id="img8" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img8",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img9" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img9",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img10" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img10",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img11" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img11",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img12" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img12",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img13" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img13",7);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img14" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img14",7);';'>
	  </div>
	</div>
</div>

<div class="row">
	  <div class="card-deck">
	  <div class="card">
         <img class="imageboxempty" id="img1" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img1",0);'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img2" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img2",0);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img3" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img3",0);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img4" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img4",0);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img5" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img5",0);';'>
	  </div>
	  <div class="card">
	     <img class="imageboxempty" id="img6" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img6",0);';'>
	  </div>
	  <div class="card" id="classimg7">

	     <img class="imageboxempty" id="img7" src="/assets/letter-empty.jpg"  onclick='changeImage(src="/assets/letter-o.jpg",gon.move,"img7",0);';'>

	  </div>
	</div>
</div>

    <div class="col-md-6">
    <div>

        <table class="table table-hover table-striped table-condensed" ng-show="movesInGame.length">
            <h2 class="lead">History of moves in the game</h2>
            <thead>
            <td>Player</td>
            <td>Position</td>
            <td>Move created</td>
            </thead>
            <tbody>
                <tr ng-repeat="move in movesInGame">
                    <td>{{move.userName}}</td>
                    <td>Board row: {{move.boardRow}}, Board column: {{move.boardColumn}}</td>
                    <td>{{move.created | date:'MM-dd-yyyy HH:mm:ss'}}</td>
                    </tr>
                    </tbody>
                </table>

                <div ng-show="!movesInGame.length">
                    No moves yet.
                </div>

    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connectfour</title>
    <%= csrf_meta_tags %>
    <%= Gon::Base.render_data %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <nav class="navbar navbar-toggleable-md navbar-light bg-faded" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">ConnectFour</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">  <%= link_to "Play", play_path, class: 'nav-link' %>
      </li>
    </ul>
   <!--  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>
    <div class="container">
    	    <%= yield %>
    </div>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_name, class: 'form-control-label' %>
    <%= form.text_field :user_name, id: :player_user_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_hash, class: 'form-control-label' %>
    <%= form.text_field :password_hash, id: :player_password_hash, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, class: 'form-control-label' %>
    <%= form.text_field :email, id: :player_email, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table class="table table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>User name</th>
      <th>Password hash</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.user_name %></td>
        <td><%= player.password_hash %></td>
        <td><%= player.email %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path, class: 'btn btn-secondary' %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @player.user_name %>
</p>

<p>
  <strong>Password hash:</strong>
  <%= @player.password_hash %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>